<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "relpat_newsfecreator"
 *
 * Auto generated by Extension Builder 2017-11-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'News Frontend Creator',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Patrick Hippler',
    'author_email' => 'info@relpat.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
